import Head from 'next/head'
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatsApp Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://web.whatsapp.com/favicon-64x64.ico" />
      </Head>
			<Sidebar />
    </div>
  )
}
